### ISSUE TITLE
use local cache in find_orchestrator

### ISSUE THREAD

**Issue by btraven00** [omnibenchmark/omnibenchmark-py#16]
depending on online lookups generates a single point of failure whenever the online infra is down. additionally, it makes it hard to develop offline.

Today there seems to be a glitch with routes:

```
❯ ping omnibenchmark.pages.uzh.ch
PING pages-uzh.cloud.switch.ch (86.119.39.48) 56(84) bytes of data.
From gitlab-uzh.cloud.switch.ch (86.119.39.48) icmp_seq=1 Destination Host Unreachable
From gitlab-uzh.cloud.switch.ch (86.119.39.48) icmp_seq=2 Destination Host Unreachable
From gitlab-uzh.cloud.switch.ch (86.119.39.48) icmp_seq=4 Destination Host Unreachable
From gitlab-uzh.cloud.switch.ch (86.119.39.48) icmp_seq=5 Destination Host Unreachable
```

Which translates into: 

```
Traceback (most recent call last):
  File "/opt/conda/bin/omni_cli", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/omni_cli/cli.py", line 125, in run
    result = workflow_run(docker_image=image, sparql=sparql, dirty=dirty)
  File "/opt/conda/lib/python3.9/site-packages/omni_cli/workflow.py", line 32, in run
    return run_from_docker(export=True, dirty=dirty)
  File "/opt/conda/lib/python3.9/site-packages/omni_cli/workflow.py", line 51, in run_from_docker
    oo = get_omni_object_from_yaml('src/config.yaml')
  File "/opt/conda/lib/python3.9/site-packages/omnibenchmark/utils/build_omni_object.py", line 352, in get_omni_object_from_yaml
    return build_omni_object_from_config(config)
  File "/opt/conda/lib/python3.9/site-packages/omnibenchmark/utils/build_omni_object.py", line 324, in build_omni_object_from_config
    omni_object = OmniObject(
  File "/opt/conda/lib/python3.9/site-packages/omnibenchmark/core/omni_object.py", line 99, in __init__
    self.orchestrator = find_orchestrator(
  File "/opt/conda/lib/python3.9/site-packages/omnibenchmark/management/general_checks.py", line 47, in find_orchestrator
    bench_html = requests.get(bench_url)
  File "/opt/conda/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='omnibenchmark.pages.uzh.ch', port=443): Max retries exceeded with url: /omb-site/p/benchmarks (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb755b864f0>: Failed to establish a new connection: [Errno 113] No route to host'))
```

We could use a local cache similar to what I'm using for `omni_cli`.

**Comment by btraven00** [comment]
alternatively, if the first fetch fails, we could return a placeholder (localhost)

**Comment by imallona** [comment]
Hi! Related but orthogonal: 
- The UZH gitlab was under maintenance from 22nd Apr to 23rd Apr, downtimes were expected (= the glitch with routes you report, I guess).
- The current omnibenchmark's webpage is at [renkulab.io's gitlab](https://renkulab.io/gitlab/omnibenchmark/omni_site), the one at [UZH's gitlab](https://gitlab.uzh.ch/omnibenchmark/omb-site/) is deprecated, sorry about this - probably not clear.

**Comment by almutlue** [comment]
Thank you both for reporting this! I think this problem was caused because I didn't update the url [here](https://github.com/omnibenchmark/omnibenchmark-py/blob/main/omnibenchmark/utils/default_global_vars.py). Sorry for this, I will fix it now and I will look into the local cache. I think it makes a lot of sense. In general, I'm not very happy about this way of fetching the orchestrator url, because it involves just another source and place we need to update for each new benchmark. I had thought about moving this to `omni_checks` once that is more mature and better structured. So basically to have one place that defines all benchmark specific variables, urls, etc.?  What do you think? That might also depend on how we (re-)design the checks?

**Comment by btraven00** [comment]
> I've documented this [now](https://gitlab.uzh.ch/omnibenchmark/omb-site/-/commit/4278f1a3e650ac8319eec71327719f7aaa8c31cc) 

perhaps it's also a good idea to archive the repo?

> I had thought about moving this to omni_checks once that is more mature and better structured. So basically to have one place that defines all benchmark specific variables, urls, etc.? 

that sounds like a good idea to me.

additionally, I think you might want to define a local-first mode. I could conceive that you recursively clone all repos in a single benchmark (i.e., namespace, or same parent folder). so you could try to traverse the filesystem one step up, and identify the orchestrator. by convention, perhaps the orchestrator repo can be named "orchestrator" (for simplicity). once there, you can see if you're behind the origin, and conceivable pass flags to force a pull etc...

**Comment by almutlue** [comment]
A local-first mode sounds good and doable. So something like 1. local-first mode, if false (default); 2. local cache, if not existing or force_update=True; 3. download from general place/omni_checks?
I guess it is reasonable to switch to one yaml file that defines all orchestrator name, url etc. relationships for this, independent how we change the structure for the checks. We can also use that yaml file to automatically populate the current table at omb-site.

I didn't use the current gitlab group structure so far, because I thought it would be good to be flexible in case someone does not want to contribute within the common benchmark namespace, but within their own namespace. I'm not sure how relevant that use case is and I'm open for feedback there?

**Comment by almutlue** [comment]
I finally updated `find_orchestrator()` and `get_benchmark_groups()` to use [this orchestrator file](https://renkulab.io/gitlab/omnibenchmark/omni_essentials/-/blob/main/general/benchmark_categories.json) from [this](https://renkulab.io/gitlab/omnibenchmark/omni_essentials) new general projects for all benchmark-specific information instead of the website. Both functions have a `local_cache` argument following your omni_cli example @btraven00. ([see this branch](https://github.com/omnibenchmark/omnibenchmark-py/tree/local_cache))

I'm afraid I struggle to fully comprehend the local-first mode:
What is the exact use case? 
In the current omnibenchmark projects the orchestrator url returned by `find_orchestrator()` is used to check project relationships for imported datasets via gitlab api, e.g. we check if the dataset is derived from a project with a successful bridge triggered by the orchestrator's cicd pipeline. This can be disabled via flag (`find_orchestrator(check_o_url = False)`). This doesn't seem to be the use case for local first mode you referred to? What about a local cache and local first mode for the [benchmark_queries](https://github.com/omnibenchmark/omnibenchmark-py/blob/main/omnibenchmark/utils/benchmark_queries.py) or more specifically the `get_orchestrator_projects_from_cicd_yaml()` function instead?

**Comment by almutlue** [comment]
I finally updated `find_orchestrator()` and `get_benchmark_groups()` to use [this orchestrator file](https://renkulab.io/gitlab/omnibenchmark/omni_essentials/-/blob/main/general/benchmark_categories.json) from [this](https://renkulab.io/gitlab/omnibenchmark/omni_essentials) new general projects for all benchmark-specific information instead of the website. Both functions have a `local_cache` argument following your omni_cli example @btraven00. ([see this branch](https://github.com/omnibenchmark/omnibenchmark-py/tree/local_cache))

I'm afraid I struggle to fully comprehend the local-first mode:
What is the exact use case? 
In the current omnibenchmark projects the orchestrator url returned by `find_orchestrator()` is used to check project relationships for imported datasets via gitlab api, e.g. we check if the dataset is derived from a project with a successful bridge triggered by the orchestrator's cicd pipeline. This can be disabled via flag (`find_orchestrator(check_o_url = False)`). This doesn't seem to be the use case for local first mode you referred to? What about a local cache and local first mode for the [benchmark_queries](https://github.com/omnibenchmark/omnibenchmark-py/blob/main/omnibenchmark/utils/benchmark_queries.py) or more specifically the `get_orchestrator_projects_from_cicd_yaml()` function instead?
